"""The timezone list, and the one place a province suggests a zone.

**Canonical names only.** `zoneinfo.available_timezones()` hands back the whole tz database
including its `backward` links — `US/Eastern`, `Asia/Calcutta`, `Canada/Eastern`, `EST`. They
still resolve, but they are aliases kept for old software, and storing one means the business
timezone is spelled differently from every other zone the app will ever print. Two spellings of
one zone in a picker is also a question nobody can answer: an administrator choosing between
`Canada/Eastern` and `America/Toronto` has no way to know they are the same clock.

**The mapping is a suggestion, and lives here alone.** Canadian provinces do not map onto
timezones: Saskatchewan skips daylight saving, the BC Kootenays are Mountain, northwestern
Ontario is Central, and Labrador spans two zones. So this picks the zone *most* of each
province is in, a human confirms it, and nothing in the app applies it on its own.
"""

from functools import lru_cache
from zoneinfo import available_timezones

# The `backward` links of the tz database, minus `Etc/*` (offsets, not places, and with an
# inverted sign that reads as a bug) and minus the bare names with no area (`EST`, `Cuba`,
# `Zulu`), which the `"/" in zone` test below removes.
#
# Generated by diffing `available_timezones()` against `zone.tab`, which lists only canonical
# zones. It is a literal rather than a read of `zone.tab` because that file is not shipped by
# the `tzdata` wheel and is therefore absent from the slim container image. A tzdata release
# that deprecates a further zone will leave it in the list until this tuple is updated —
# a stale entry is a name that still works, which is the harmless direction.
DEPRECATED: frozenset[str] = frozenset(
    (
        "Africa/Asmera", "Africa/Timbuktu", "America/Argentina/ComodRivadavia", "America/Atka",
        "America/Buenos_Aires", "America/Catamarca", "America/Coral_Harbour", "America/Cordoba",
        "America/Ensenada", "America/Fort_Wayne", "America/Godthab", "America/Indianapolis",
        "America/Jujuy", "America/Knox_IN", "America/Louisville", "America/Mendoza",
        "America/Montreal", "America/Nipigon", "America/Pangnirtung", "America/Porto_Acre",
        "America/Rainy_River", "America/Rosario", "America/Santa_Isabel", "America/Shiprock",
        "America/Thunder_Bay", "America/Virgin", "America/Yellowknife", "Antarctica/South_Pole",
        "Asia/Ashkhabad", "Asia/Calcutta", "Asia/Choibalsan", "Asia/Chongqing", "Asia/Chungking",
        "Asia/Dacca", "Asia/Harbin", "Asia/Istanbul", "Asia/Kashgar", "Asia/Katmandu",
        "Asia/Macao", "Asia/Rangoon", "Asia/Saigon", "Asia/Tel_Aviv", "Asia/Thimbu",
        "Asia/Ujung_Pandang", "Asia/Ulan_Bator", "Atlantic/Faeroe", "Atlantic/Jan_Mayen",
        "Australia/ACT", "Australia/Canberra", "Australia/Currie", "Australia/LHI",
        "Australia/NSW", "Australia/North", "Australia/Queensland", "Australia/South",
        "Australia/Tasmania", "Australia/Victoria", "Australia/West", "Australia/Yancowinna",
        "Brazil/Acre", "Brazil/DeNoronha", "Brazil/East", "Brazil/West", "Canada/Atlantic",
        "Canada/Central", "Canada/Eastern", "Canada/Mountain", "Canada/Newfoundland",
        "Canada/Pacific", "Canada/Saskatchewan", "Canada/Yukon", "Chile/Continental",
        "Chile/EasterIsland", "Europe/Belfast", "Europe/Kiev", "Europe/Nicosia",
        "Europe/Tiraspol", "Europe/Uzhgorod", "Europe/Zaporozhye", "Mexico/BajaNorte",
        "Mexico/BajaSur", "Mexico/General", "Pacific/Enderbury", "Pacific/Johnston",
        "Pacific/Ponape", "Pacific/Samoa", "Pacific/Truk", "Pacific/Yap", "US/Alaska",
        "US/Aleutian", "US/Arizona", "US/Central", "US/East-Indiana", "US/Eastern", "US/Hawaii",
        "US/Indiana-Starke", "US/Michigan", "US/Mountain", "US/Pacific", "US/Samoa",
    )
)  # fmt: skip


# The one zone with no area that stays. It is what an operator means by "no local time" — a
# test instance, a lab, a deployment that has not decided yet — and the wizard accepted it
# before this filter existed, so dropping it would strand any row already holding it in a
# picker that cannot re-select its own value. `Etc/UTC` is the same clock under the spelling
# nobody types, and it stays out with the rest of `Etc/`.
KEPT_WITHOUT_AREA = frozenset({"UTC"})


@lru_cache
def canonical_timezones() -> tuple[str, ...]:
    """Every IANA zone an administrator may choose, sorted."""
    return tuple(
        sorted(
            zone
            for zone in available_timezones()
            if zone not in DEPRECATED
            and not zone.startswith("Etc/")
            and ("/" in zone or zone in KEPT_WITHOUT_AREA)
        )
    )


def is_canonical(zone: str) -> bool:
    return zone in canonical_timezones()


# Code → (name, the zone most of it keeps). The name is here because the select on the
# Business screen reads from this list, so the two can never disagree about the thirteen.
#
# The Northwest Territories are `America/Edmonton`, not `America/Yellowknife`: tzdata 2023a
# made Yellowknife a link to Edmonton. Same clock, same history, a name that is not deprecated.
PROVINCES: dict[str, tuple[str, str]] = {
    "AB": ("Alberta", "America/Edmonton"),
    "BC": ("British Columbia", "America/Vancouver"),
    "MB": ("Manitoba", "America/Winnipeg"),
    "NB": ("New Brunswick", "America/Halifax"),
    "NL": ("Newfoundland and Labrador", "America/St_Johns"),
    "NS": ("Nova Scotia", "America/Halifax"),
    "NT": ("Northwest Territories", "America/Edmonton"),
    "NU": ("Nunavut", "America/Iqaluit"),
    "ON": ("Ontario", "America/Toronto"),
    "PE": ("Prince Edward Island", "America/Halifax"),
    "QC": ("Quebec", "America/Toronto"),
    "SK": ("Saskatchewan", "America/Regina"),
    "YT": ("Yukon", "America/Whitehorse"),
}
